### ISSUE TITLE
BUG: Bulldog Magazine Articles are Missing

### ISSUE THREAD

**Issue by BeckyMedlin** [aemsites/vg-macktrucks-com#128] opened 2024-12-10 17:23 UTC
### Issue Type

Bug

### Summary

Mack Bulldog category pages do not display articles and article search by category returns no results. 

### Priority

High

### Description

Impact to production: The articles that should display on the following pages in all of the Bulldog Magazine categories (all categories under "Loading Dock" header) do not display:

- https://www.macktrucks.com/magazine/categories/customer-profiles
- https://www.macktrucks.com/magazine/categories/product-updates
- https://www.macktrucks.com/magazine/categories/technology-at-work
- https://www.macktrucks.com/magazine/categories/features
- https://www.macktrucks.com/magazine/categories/in-the-news
- https://www.macktrucks.com/magazine/categories/viewpoint

### Affected Device Classes

Desktop, Mobile, Tablet

### Affected Browsers/Devices and Versions

Chrome and Edge

### Steps to Reproduce

1. Navigate to Bulldog Magazine section from home page (Experience>Explore & Experience>Bulldog Magazine)
2. Scroll down to Loading Dock section
3. Select any of the categories (Customer Profiles, Product Updates, Technology at Work, Features, In the News, and Viewpoint) and the selected category page does not display any articles. 
4. Selecting Explore All Articles CTA and searching for articles by specifying a category returns no results, except for "All Categories," which displays 85 articles. 

### Expected Results

Articles will display for each category and user will be able to find articles by searching by category. 

### Actual Results

No articles display. No search for articles by category returns results. 

### Attachment

![Image](https://github.com/user-attachments/assets/95cae2e9-4408-4236-abc3-27e2b2d16da3)
![Image](https://github.com/user-attachments/assets/24e79b0d-4b89-4914-a834-bc72f0d26cc0)
![Image](https://github.com/user-attachments/assets/c329ec30-ddab-40b8-ab0b-5adc0be45497)

**Comment by Varunvolvo** [comment] 2024-12-10 17:44
Thankyou for guiding me on the steps @santi-homps. The issue is now sorted and all the magazine articles are displaying in each category.

**Comment by santi-homps** [comment] 2024-12-10 17:53
This issue will re-occur if the `magazine-articles.json` query is re-triggered since all the articles now have been published replacing `category` for `article-category`.
The definitive fix for this will come with completion of issue #127 that depends as well on issue #106 currently blocked by work done by the search team.

**Comment by AsmitKMishra** [comment] 2024-12-11 12:08
Testing Completed. Bug is fixed and articles are displayed as expected.
![Uploading Screenshot 2024-12-11 173422.png…]()
![Uploading Screenshot 2024-12-11 173359.png…]()

**Comment by AsmitKMishra** [comment] 2024-12-11 12:10
<img width="960" alt="Screenshot 2024-12-11 173422" src="https://github.com/user-attachments/assets/fa8fa524-fdce-46cc-aa9f-f8ec65ba929a">
<img width="960" alt="Screenshot 2024-12-11 173359" src="https://github.com/user-attachments/assets/efd0faaf-5ca3-4dc7-9b18-3f58c4dad360">

**Closed** 2024-12-18 09:16 UTC
Labels: Triage, Bugfix, Injection
